name: Build iOS IPA
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install xcodegen

      - name: Run Build Script
        run: |
          chmod +x dev.sh
          ./dev.sh

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: OpenDIHM-IPA
          path: build/*.ipa
